### ISSUE TITLE
Correction to coding rules 

### ISSUE THREAD

**Issue by lari-kannisto** [dslmeinte/dcc-encoding#1]
The coding in cases with recovery show incorrect vaccination dose info in dn/sd -fields.
https://dcc-encoding.vercel.app/?events=2V,R,2V
The recovery should not increase the dn value but should decrease the sd value. In this case the first DCC can be reissued as 1/1.
event #  | event | dn | sd
   1         |   2V   |  1  |  2
   **2         |    R    |  1  |  1**
   3         |   2V   |  2  |  1

https://dcc-encoding.vercel.app/?events=2V,2V,R,2V
The booster vaccination should be marked 3/3 as recovery should not affect the vaccination markings after complete vaccination course.

event #  | event | dn | sd
   1         |   2V   |  1  |  2
   2         |   2V   |  2  |  2
   3         |    R    |  2  |  2
   **4         |   2V   |  3  |  3**

**Comment by dslmeinte** [comment]
Hi @lari-kannisto ,

1. Why would you want to re-issue the DCC from step 2 at all? The sequence `2V,R` has been recognised as sufficiently equivalent to a full primary course with a 2-dose vaccine. I don't see the point of re-issuing previous DCCs (and revoking the original DCCs!) based on later events. I also don't see a reason to interpret EU Regulations that way, but I'm curious if you do see a way.

2. I see your point here, I think: the recovery doesn't function as a substitute for 1 vaccination in a 2-dose vaccination course. I'll try and fix that shortly.

**Comment by dslmeinte** [comment]
I just deployed a new version of the mini-app with re-worked logic. The 2nd scenario is now fixed.

**Comment by lari-kannisto** [comment]
Consider the following scenario:
First event 2V.  After 30 days person is tested positive = R. R is valid for 180 days from the positive test, but the 1/1 DCC would be valid for another 60  days as complete vaccination set (270 days from the vaccination).

**Comment by dslmeinte** [comment]
Ah, like that. This simulation doesn't take time into account at all, in any way. The EU Regulations, which this mini-app is meant to simulate, don't say anything about what `dn/sd` values to issue with taking time into consideration, so that matches.

I certainly agree that a sequence of events is a too simple way to model epidemiological reality. It's just not reflected in the Regs (yet), at the moment.
